spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/emtalik-database
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true